blueprint:
  name: Feu de Camp (optimisé IKEA - Color Temp)
  description: Effet feu de camp simulé via des variations de température de couleur, compatible avec ampoules IKEA TRÅDFRI.
  domain: automation
  input:
    ampoules:
      name: Ampoules IKEA
      selector:
        entity:
          domain: light
          multiple: true
    repetitions:
      name: Nombre de cycles
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "x"
          mode: slider

trigger: []

condition: []

action:
  - repeat:
      count: !input repetitions
      sequence:
        - variables:
            temp_1: [370, 400, 450, 500]
            temp_2: [330, 370, 420, 460]
        - repeat:
            for_each: !input ampoules
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item }}"
                  color_temp: "{{ temp_1[loop.index0 % temp_1 | length] }}"
                  brightness: 200
                  transition: 1
        - delay: "00:00:02"
        - repeat:
            for_each: !input ampoules
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item }}"
                  color_temp: "{{ temp_2[loop.index0 % temp_2 | length] }}"
                  brightness: 170
                  transition: 1
        - delay: "00:00:02"
