blueprint:
  name: Feu de Camp RGB (version stable avec index dynamique)
  description: >
    Simule un feu de camp RGB avec couleurs chaudes, compatible IKEA.
    L'effet attribue des couleurs différentes à chaque ampoule à chaque étape.
  domain: automation
  input:
    ampoules:
      name: Ampoules RGB
      selector:
        entity:
          domain: light
          multiple: true
    repetitions:
      name: Nombre de cycles
      default: 6
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: "x"
          mode: slider

trigger: []

condition: []

action:
  - repeat:
      count: !input repetitions
      sequence:
        - variables:
            couleurs1: [[255, 60, 10], [255, 90, 20], [255, 120, 40], [230, 70, 30]]
            couleurs2: [[220, 40, 5], [255, 70, 15], [255, 100, 30], [200, 50, 20]]
        - repeat:
            for_each: >
              {% set result = [] %}
              {% for i in range(inputs.ampoules | length) %}
                {% set result = result + [{'entity_id': inputs.ampoules[i], 'index': i}] %}
              {% endfor %}
              {{ result }}
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item.entity_id }}"
                  rgb_color: "{{ couleurs1[repeat.item.index % couleurs1 | length] }}"
                  brightness: 200
                  transition: 3
        - delay: "00:00:05"
        - repeat:
            for_each: >
              {% set result = [] %}
              {% for i in range(inputs.ampoules | length) %}
                {% set result = result + [{'entity_id': inputs.ampoules[i], 'index': i}] %}
              {% endfor %}
              {{ result }}
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item.entity_id }}"
                  rgb_color: "{{ couleurs2[repeat.item.index % couleurs2 | length] }}"
                  brightness: 180
                  transition: 3
        - delay: "00:00:05"
