blueprint:
  name: Feu de Camp RGB (Script)
  description: >
    Simule un feu de camp RGB chaud, en attribuant des teintes différentes à chaque ampoule.
    Fonctionne avec des ampoules IKEA RGB, avec transitions lentes pour éviter les erreurs.
  domain: script
  input:
    ampoules:
      name: Ampoules RGB
      description: Sélectionne les ampoules RGB à inclure
      selector:
        entity:
          domain: light
          multiple: true
    repetitions:
      name: Nombre de cycles
      default: 6
      selector:
        number:
          min: 1
          max: 30
          mode: slider
          unit_of_measurement: "x"

sequence:
  - variables:
      couleurs1:
        - [255, 60, 10]
        - [255, 90, 20]
        - [255, 120, 40]
        - [230, 70, 30]
      couleurs2:
        - [220, 40, 5]
        - [255, 70, 15]
        - [255, 100, 30]
        - [200, 50, 20]
  - repeat:
      count: !input repetitions
      sequence:
        - variables:
            ampoules_indexees: >
              {% set out = [] %}
              {% for i in range(ampoules | length) %}
                {% set out = out + [{'entity_id': ampoules[i], 'index': i}] %}
              {% endfor %}
              {{ out }}
        - repeat:
            for_each: "{{ ampoules_indexees }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item.entity_id }}"
                  rgb_color: "{{ couleurs1[repeat.item.index % couleurs1 | length] }}"
                  brightness: 200
                  transition: 3
        - delay: "00:00:05"
        - repeat:
            for_each: "{{ ampoules_indexees }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item.entity_id }}"
                  rgb_color: "{{ couleurs2[repeat.item.index % couleurs2 | length] }}"
                  brightness: 180
                  transition: 3
        - delay: "00:00:05"

mode: single
