blueprint:
  name: Feu de Camp RGB (IKEA-compatible, version finale)
  description: >
    Simule un feu de camp avec variations RGB chaudes. Compatible IKEA.
    Applique des couleurs différentes par ampoule, avec transitions douces.
  domain: automation
  input:
    ampoules:
      name: Ampoules RGB IKEA
      selector:
        entity:
          domain: light
          multiple: true
    repetitions:
      name: Nombre de cycles
      default: 6
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: "x"
          mode: slider

trigger: []

condition: []

action:
  - repeat:
      count: !input repetitions
      sequence:
        - variables:
            couleurs1: [[255, 60, 10], [255, 90, 20], [255, 120, 40], [230, 70, 30]]
            couleurs2: [[220, 40, 5], [255, 70, 15], [255, 100, 30], [200, 50, 20]]
        - variables:
            index: 0
        - repeat:
            for_each: !input ampoules
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item }}"
                  rgb_color: "{{ couleurs1[index % couleurs1 | length] }}"
                  brightness: 200
                  transition: 3
              - variables:
                  index: "{{ index + 1 }}"
        - delay: "00:00:05"
        - variables:
            index: 0
