blueprint:
  name: Feu de Camp Flexible (multi-ampoules RGB)
  description: Simule un feu de camp avec des couleurs chaudes variant doucement sur un nombre illimité d'ampoules RGB.
  domain: automation
  input:
    ampoules:
      name: Ampoules RGB
      selector:
        entity:
          domain: light
          multiple: true
    repetitions:
      name: Nombre de cycles
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "x"
          mode: slider

trigger: []

condition: []

action:
  - repeat:
      count: !input repetitions
      sequence:
        - variables:
            couleurs1: [[255, 60, 10], [230, 100, 20], [255, 120, 40], [200, 80, 30]]
            couleurs2: [[220, 40, 5], [255, 90, 30], [240, 70, 15], [255, 110, 60]]
        - repeat:
            for_each: !input ampoules
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item }}"
                  rgb_color: "{{ couleurs1[loop.index0 % couleurs1 | length] }}"
                  brightness: 180
                  transition: 1.5
        - delay: "00:00:02"
        - repeat:
            for_each: !input ampoules
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ repeat.item }}"
                  rgb_color: "{{ couleurs2[loop.index0 % couleurs2 | length] }}"
                  brightness: 190
                  transition: 1.5
        - delay: "00:00:02"
